[tools]
go = "latest"
node = "latest"
python = "latest"
java = "11"
poetry = "latest"
uv = "latest"
lazygit = "latest"
pnpm = "latest"
lazydocker = "latest"
rust = "latest"
neovim = "latest"
zellij = "latest"
